cursor            #ffb59d
cursor_text_color #55200d

foreground            #f1dfda
background            #140c0a
selection_foreground  #442a21
selection_background  #e7bdb1
url_color             #e7bdb1

#: black 000000 767676
color0  #1a110f
color8  #3d322f
#: red cc0403 f2201f
color1  #30241f
color9  #8c695c
#: green 19cb00 23fd00
color2  #e7bdb1
color10 #ffdbd0
#: yellow cecb00 fffd00
color3  #d7c68d
color11 #f4e2a7
#: blue 0d73cc 1a8fff
color4  #723521
color12 #ffb59d
#: magenta cb1ed1 fd28ff
color5  #5d4036
color13 #e7bdb1
#: cyan 0dcdcd 14ffff
color6  #51461a
color14 #d7c68d
#: white dddddd ffffff
color7  #d8c2bb
color15 #f1dfda

mark1_foreground #390b00
mark1_background #ffdbd0
mark2_foreground #2c160e
mark2_background #ffdbd0
mark3_foreground #221b00
mark3_background #f4e2a7

active_tab_foreground #55200d
active_tab_background #ffb59d
inactive_tab_foreground #ffdbd0
inactive_tab_background #723521

active_border_color #ffb59d
inactive_border_color #55200d
# bell_border_color #ff5a00
