# --- Main Colors ---
background            #121318
foreground            #e3e1e9
cursor                #e3e1e9
cursor_text_color     #121318

selection_background  #414659
selection_foreground  #dde1f9

url_color             #e2bbdb

# --- ANSI Colors ---
color0                #121318
color1                #ffb4ab
color2                #e2bbdb
color3                #c1c5dd
color4                #b5c4ff
color5                #e2bbdb
color6                #c1c5dd
color7                #e3e1e9

color8                #45464f
color9                #93000a
color10               #5b3d57
color11               #414659
color12               #334479
color13               #414659
color14               #5b3d57
color15               #c6c6d0

# --- Starship Prompt Bubbles ---
color255              #334479
color254              #b5c4ff
color253              #414659
color252              #c1c5dd
color251              #5b3d57
color250              #e2bbdb
color249              #93000a
color248              #ffb4ab

color232              #dbe1ff
color233              #1b2d61
color234              #dde1f9
color235              #2b3042
color236              #ffd6f7
color237              #422740
color238              #ffdad6
color239              #690005
color240              #dbe1ff

# Matched with unthemed light/dark
color243              #b5c4ff
color244              #ffb4ab
color245              #45464f

# --- UI Elements ---
active_tab_foreground   #1b2d61
active_tab_background   #b5c4ff
inactive_tab_foreground #dbe1ff
inactive_tab_background #334479

active_border_color     #b5c4ff
inactive_border_color   #8f909a

# --- Marks ---
mark1_foreground        #01174b
mark1_background        #dbe1ff
mark2_foreground        #161b2c
mark2_background        #dde1f9
mark3_foreground        #2b122a
mark3_background        #ffd6f7
