$image = Screenshot (61).png

$background = rgba(131318ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(303036ff)

$inverse_primary = rgba(545a92ff)

$inverse_surface = rgba(e4e1e9ff)

$on_background = rgba(e4e1e9ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(252b61ff)

$on_primary_container = rgba(dfe0ffff)

$on_primary_fixed = rgba(0f154bff)

$on_primary_fixed_variant = rgba(3c4279ff)

$on_secondary = rgba(2d2f42ff)

$on_secondary_container = rgba(e1e0f9ff)

$on_secondary_fixed = rgba(181a2cff)

$on_secondary_fixed_variant = rgba(444559ff)

$on_surface = rgba(e4e1e9ff)

$on_surface_variant = rgba(c7c5d0ff)

$on_tertiary = rgba(45263cff)

$on_tertiary_container = rgba(ffd7efff)

$on_tertiary_fixed = rgba(2e1126ff)

$on_tertiary_fixed_variant = rgba(5e3c53ff)

$outline = rgba(91909aff)

$outline_variant = rgba(46464fff)

$primary = rgba(bdc2ffff)

$primary_container = rgba(3c4279ff)

$primary_fixed = rgba(dfe0ffff)

$primary_fixed_dim = rgba(bdc2ffff)

$scrim = rgba(000000ff)

$secondary = rgba(c4c4ddff)

$secondary_container = rgba(444559ff)

$secondary_fixed = rgba(e1e0f9ff)

$secondary_fixed_dim = rgba(c4c4ddff)

$shadow = rgba(000000ff)

$source_color = rgba(a6a8cbff)

$surface = rgba(131318ff)

$surface_bright = rgba(39393fff)

$surface_container = rgba(1f1f25ff)

$surface_container_high = rgba(29292fff)

$surface_container_highest = rgba(34343aff)

$surface_container_low = rgba(1b1b21ff)

$surface_container_lowest = rgba(0d0e13ff)

$surface_dim = rgba(131318ff)

$surface_tint = rgba(bdc2ffff)

$surface_variant = rgba(46464fff)

$tertiary = rgba(e7b9d6ff)

$tertiary_container = rgba(5e3c53ff)

$tertiary_fixed = rgba(ffd7efff)

$tertiary_fixed_dim = rgba(e7b9d6ff)

