#!/bin/bash 

IMAGE="$1"

wal -i "$IMAGE" -n

killall -9 waybar
waybar > /dev/null 2>&1 &

swaync-client -R
swaync-client -rs

swww img "$IMAGE" --transition-type grow
cp "$IMAGE" /opt/wal.png

notify-send "Wallpaper and colorscheme changed to $IMAGE"
