#!/bin/env bash 

# Check if an image path was provided
if [ -z "$1" ]; then
    echo "Usage: ./wallpaper.sh /path/to/image.png"
    exit 1
fi

IMAGE="$1"

# Generate colorscheme (Matugen)
matugen image "$IMAGE"

# Restart Waybar
pkill waybar
(waybar > /dev/null 2>&1 &)

# Refresh SwayNotificationCenter
swaync-client -R
swaync-client -rs

# Update Wallpaper with swww
awww img "$IMAGE" --transition-type random

# Update global wallpaper reference
cp "$IMAGE" /opt/wal.png

# Notify
notify-send "System Theme Updated" "Wallpaper changed to $(basename "$IMAGE")" -i "$IMAGE"
